version: '3'

services:
  music_insights:
    container_name: music_insights
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./music_insights:/music_insights
    networks:
      - local_network
    restart: "no"
  
networks:
  local_network:
    driver: bridge
