name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          flake8 .
      - name: isort
        run: |
          isort . --check-only --diff
      - name: Test with pytest and coverage
        run: |
          pytest --cov=music_insights test
      - name: mypy
        run: |
          mypy
