name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r music_insights/requirements-dev.txt
      - name: Lint with flake8
        run: |
          flake8 music_insights/main.py
          flake8 music_insights/music_insights
          flake8 music_insights/test
      - name: isort
        run: |
          isort music_insights/main.py --check-only --diff
          isort music_insights/music_insights --check-only --diff
          isort music_insights/test --check-only --diff
      - name: Test with pytest
        run: |
          pytest music_insights/test
